### ISSUE TITLE
Grasshopper for Mac wont load after installing rehopper

### ISSUE THREAD

**Issue by JBENEITEZ** [NoDoubtsKleve/rehopper#1]
Tried with Rhino 7 and 8 WIP. After installing Rehopper using the package manager, when restarting GH, the loading bar will reach 100% but gets stuck there without disappearing or showing the canvas

**Comment by thekaushikls** [comment]
@JBENEITEZ Issue is fixed,  tested on `MacBookPro Intel 2017` and `Rhino 7.13`. Enjoy! 🚀

![Issue_1_Fixed](https://github.com/NoDoubtsKleve/rehopper/assets/50703773/b897a647-a35b-446f-b655-449458fe61d5)
